is_train: True # train deepsvdd
is_rag: True # use post processing stage
dataset_name: KUBE
train_ratio: 0.8
window_size: 200 
window_time: 1800 # 30 minutes

# openai key
api_key: xxxxxxxxxxxxxxxxxxxx
api_base: xxxxxxxxxxxxxxxxxx

#llm_name: gpt-3.5-turbo
llm_name: qwen-max
# llm_name: mistralai/Mistral-7B-Instruct-v0.1 # from huggingface

# deepsvdd parameters
optimizer_name: adam
lr: 0.0001
n_epochs: 150
lr_milestones: [50]
batch_size: 40960
weight_decay: 0.0005
#device: cuda:0
device: cpu
n_jobs_dataloader: 0

# rag parameters
threshold: 0.8
topk: 5
prompt: PROMPT_C1_2
persist_directory: ./output/ragdb-kube
