# System configuration
device: cuda:0
output_dir: outputs
is_rag: True # use post processing stage
dataset_name: KUBE
regenerate_graphs: false

# openai key
api_key: xxxxxxxxxxxxxxxxxxxx
api_base: xxxxxxxxxxxxxxxxxx

#llm_name: gpt-3.5-turbo
llm_name: qwen-max

# Model configuration
model: DiGCN
hidden_dim: 128
layers: 2
bias: false
aggregation: Mean

# Training configuration
batch_size: 32
epochs: 150
lr: 0.01
weight_decay: 0.0001
alpha: 1.0
beta: 0.0

# rag parameters
threshold: 0.8
topk: 5
prompt: PROMPT_C1_2
persist_directory: ./output/ragdb-kube
